language: c++

sudo: required

dist: xenial

matrix:
  include:
  - compiler: clang
    env: MAKEVARS=CPPFLAGS=-Werror
  - compiler: clang
    env:
      - MAKEVARS=CPPFLAGS=-Werror
      - CONFIGURE_OPTS=--with-crypto-impl=openssl
  - compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y bison dejagnu gettext keyutils ldap-utils libcmocka-dev libldap2-dev libkeyutils-dev libssl-dev python3-kdcproxy python3-pip slapd tcl-dev tcsh
  - pip3 install pyrad

script: sh -ex .travis-ci.sh
